ALTER TABLE [User]
ALTER Column PhoneNumber NVARCHAR(13) NOT NULL

ALTER TABLE [User]
ADD CONSTRAINT UQ_User_PhoneNumber UNIQUE (PhoneNumber);

ALTER TABLE [User]
ADD CONSTRAINT DF_User_IsDeleted DEFAULT 0 FOR IsDeleted;

ALTER TABLE Book
ADD CONSTRAINT DF_Book_IsDeleted DEFAULT 0 FOR IsDeleted;