CREATE DATABASE DigitalLibraryDb

USE DigitalLibraryDb

CREATE TABLE Categories(
	Id INT PRIMARY KEY IDENTITY,
	Title NVARCHAR(255) NOT NULL
)
CREATE TABLE Roles(
	Id INT PRIMARY KEY IDENTITY,
	Title NVARCHAR(255) NOT NULL
)
CREATE TABLE Books(
	Id INT PRIMARY KEY IDENTITY,
	Title NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(MAX),
	ImageUrl NVARCHAR(MAX),
	FileUrl NVARCHAR(MAX),
	Author NVARCHAR(255),
	CategoryId INT,
	IsDeleted bit NOT NULL DEFAULT 0,
	CONSTRAINT FK_Books_Categories FOREIGN KEY (CategoryId)
		REFERENCES Categories(Id)
)
CREATE TABLE Users(
	Id INT PRIMARY KEY IDENTITY,
	FullName NVARCHAR(255) NOT NULL,
	PhoneNumber NVARCHAR(11) NOT NULL,
	[Password] NVARCHAR(MAX) NOT NULL,
	RoleId INT,
	IsDeleted bit NOT NULL DEFAULT 0,
	CONSTRAINT FK_Users_Roles FOREIGN KEY (RoleId)
		REFERENCES Roles(Id),
	CONSTRAINT UQ_Users_PhoneNumber UNIQUE (PhoneNumber)
)
CREATE TABLE DownloadedBooks(
	Id INT PRIMARY KEY IDENTITY,
	BookId INT,
	UserId INT,
	CONSTRAINT FK_DownloadedBooks_Users FOREIGN KEY (UserId) 
		REFERENCES Users(Id),
	CONSTRAINT FK_DownloadedBooks_Books FOREIGN KEY (BookId) 
		REFERENCES Books(Id)
)