--Displays all customers located in London
CREATE VIEW vw_LondonCustomers
AS
SELECT CustomerID, CustomerName, City
FROM Customers
WHERE City = 'London';

--Select all customers from London
SELECT * FROM vw_LondonCustomers;


--Displays all orders with their corresponding customer names
CREATE VIEW vw_CustomerOrders
AS
SELECT 
    c.CustomerName, 
    o.OrderID, 
    o.OrderDate
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID;

--Show all customer orders with order details
SELECT * FROM vw_CustomerOrders;


--Shows total quantity and total revenue for each product
CREATE VIEW vw_TopSellingProducts
AS
SELECT 
    p.ProductID,
    p.ProductName,
    SUM(od.Quantity) AS TotalSold,                -- Total number of units sold
    SUM(od.Quantity * p.Price) AS TotalRevenue    -- Total sales revenue per product
FROM Products p
LEFT JOIN Order_Details od ON p.ProductID = od.ProductID
GROUP BY p.ProductID, p.ProductName;

--Display all products with their total sales and revenue
SELECT * FROM vw_TopSellingProducts;


--Displays employee performance (total orders and total sales)
CREATE VIEW vw_EmployeePerformance
AS
SELECT 
    e.EmployeeID,
    e.FirstName + ' ' + e.LastName AS EmployeeName, -- Combine first and last name
    COUNT(o.OrderID) AS TotalOrders,                -- Number of orders handled by employee
    SUM(od.Quantity * p.Price) AS TotalSales        -- Total sales generated by employee
FROM Employees e
LEFT JOIN Orders o ON e.EmployeeID = o.EmployeeID
LEFT JOIN Order_Details od ON o.OrderID = od.OrderID
LEFT JOIN Products p ON od.ProductID = p.ProductID
GROUP BY e.EmployeeID, e.FirstName, e.LastName;

--Show performance metrics for each employee
SELECT * FROM vw_EmployeePerformance;
