CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'MyStrongPassword@2025'

CREATE CERTIFICATE CustomerDataCert
WITH SUBJECT = 'Encrypt customer data'

CREATE SYMMETRIC KEY CustomerSymKey
WITH ALGORITHM = AES_256
ENCRYPTION BY CERTIFICATE CustomerDataCert;

ALTER TABLE Customers
ADD EncryptedCountry VARBINARY(MAX)

OPEN SYMMETRIC KEY CustomerSymKey DECRYPTION BY CERTIFICATE CustomerDataCert

UPDATE customers
SET EncryptedCountry = ENCRYPTBYKEY(KEY_GUID('CustomerSymKey'),Country)

CLOSE SYMMETRIC KEY CustomerSymKey


OPEN SYMMETRIC KEY CustomerSymKey DECRYPTION BY CERTIFICATE CustomerDataCert

SELECT CustomerId, ContactName, CONVERT(VARCHAR(255), DECRYPTBYKEY(EncryptedCountry)) AS DecryptedCountry
FROM customers

CLOSE SYMMETRIC KEY CustomerSymKey