CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'MyStrongPassword@2025'
OPEN MASTER KEY DECRYPTION BY PASSWORD = 'MyStrongPassword@2025'

CREATE CERTIFICATE MyTDECert
WITH SUBJECT = 'Encrypt Db Files'

USE TopTest
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE MyTDECert

ALTER DATABASE TopTest
SET ENCRYPTION ON


SELECT name, is_encrypted from sys.databases
